const mongoose = require("mongoose");

const studentSchema = mongoose.Schema({
  _id: mongoose.Schema.Types.ObjectId, //unique id for each student
  name: { type: String, required: true }, //Students name
  phone: { type: Number, required: true },
  email: { type: String, required: true, unique: true }, //students email
  reg_no: { type: Number, required: true, unique: true }, //students reg_no
  password: { type: String, required: true }, //encrypted password
  floor_warden_id: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Teacher",
    required: true,
  }, //floor warder unique_id(the one generated by mongoose)
  hostel: { type: String, required: true }, //hostel no eg:- Hostel-1
  block: { type: String, required: true }, //hostel block eg:- I
  room: { type: Number, required: true }, //hostel room eg:- 603
  level: { type: Number, required: true }, //hostel floor no
  parents_phone: { type: Number, required: true }, //Parents phone no
  department: { type: String, required: true }, //student department
  year: { type: String, required: true }, //student year
});

module.exports = mongoose.model("Student", studentSchema);
